# Generated by Django 2.1.4 on 2018-12-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessListOfDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_user', models.CharField(max_length=30)),
                ('device_model', models.CharField(default='', max_length=30)),
                ('access_id_path', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressLoginsSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('site_url', models.CharField(default='', max_length=100)),
                ('site_uid', models.CharField(default='', max_length=50)),
                ('site_pid', models.CharField(default='', max_length=50)),
                ('s_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='NewAccountLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_target_url', models.CharField(max_length=200)),
                ('login_name', models.CharField(max_length=200)),
                ('login_username', models.CharField(max_length=200)),
                ('login_password', models.CharField(max_length=200)),
                ('login_notes', models.CharField(max_length=200)),
                ('login_user', models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='PinaxPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_point_values', models.CharField(max_length=200)),
                ('point_values', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TempAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_uname', models.CharField(max_length=30)),
                ('temp_pword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('notes', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(default='', on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
