# Generated by Django 2.1.3 on 2018-11-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HavenFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_haven_folder', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAccountLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_target_url', models.CharField(max_length=200)),
                ('login_name', models.CharField(max_length=200)),
                ('login_username', models.CharField(max_length=200)),
                ('login_password', models.CharField(max_length=200)),
                ('login_notes', models.CharField(max_length=200)),
                ('login_haven_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comhavenapp.HavenFolder', to_field='login_haven_folder')),
            ],
        ),
        migrations.CreateModel(
            name='NewHavenFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_haven_folder', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinaxPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_point_values', models.CharField(max_length=200)),
                ('point_values', models.CharField(max_length=200)),
            ],
        ),
    ]
