# Generated by Django 2.1.4 on 2019-01-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressloginssites',
            name='site_pid',
        ),
        migrations.RemoveField(
            model_name='expressloginssites',
            name='site_uid',
        ),
    ]
