# Generated by Django 2.0.9 on 2018-12-10 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslistofdevices',
            name='acl_user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tempaccounts',
            name='temp_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
