# Generated by Django 2.1.4 on 2019-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaccountlogin',
            name='flag',
            field=models.CharField(default='', max_length=10),
        ),
    ]
