# Generated by Django 2.1.4 on 2019-01-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressloginssites',
            name='s_user',
        ),
    ]
