# Generated by Django 2.1.4 on 2019-02-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='user',
        ),
    ]
