# Generated by Django 2.1.4 on 2019-01-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0002_duplicatepasswords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatepasswords',
            name='login_score',
        ),
        migrations.RemoveField(
            model_name='duplicatepasswords',
            name='login_strength',
        ),
    ]
