# Generated by Django 2.1.3 on 2018-11-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havenfolder',
            name='login_haven_folder',
            field=models.CharField(default='Folder', max_length=200, unique=True),
        ),

    ]
