# Generated by Django 2.1.4 on 2019-01-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0002_auto_20190120_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaccountlogin',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='overall_points',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
