# Generated by Django 2.1.4 on 2019-01-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0003_auto_20190126_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisedpasswords',
            name='login_score',
        ),
        migrations.RemoveField(
            model_name='compromisedpasswords',
            name='login_strength',
        ),
        migrations.RemoveField(
            model_name='oldpasswords',
            name='login_score',
        ),
        migrations.RemoveField(
            model_name='oldpasswords',
            name='login_strength',
        ),
        migrations.AddField(
            model_name='oldpasswords',
            name='date_last_inserted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
