# Generated by Django 2.1.4 on 2019-01-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0003_passwordgenerator_pass_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordgenerator',
            name='user',
        ),
        migrations.AlterField(
            model_name='passwordgenerator',
            name='pass_result',
            field=models.CharField(default='res', max_length=200),
        ),
    ]
