# Generated by Django 2.1.1 on 2018-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccountLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_target_url', models.CharField(max_length=200)),
                ('login_name', models.CharField(max_length=200)),
                ('login_haven_folder', models.CharField(max_length=200)),
                ('login_username', models.CharField(max_length=200)),
                ('login_password', models.CharField(max_length=200)),
                ('login_notes', models.CharField(max_length=200)),
            ],
        ),
    ]
