# Generated by Django 2.0.9 on 2018-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0003_auto_20181128_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havenfolder',
            name='login_haven_folder',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
