# Generated by Django 2.1.3 on 2018-11-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0004_newaccountlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HavenFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_haven_folder', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='newaccountlogin',
            name='login_haven_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comhavenapp.HavenFolder', to_field='login_haven_folder'),
        ),
    ]
