# Generated by Django 2.1.4 on 2019-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0004_tempaccounts_ch_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaccountlogin',
            name='issue_flag',
            field=models.BooleanField(default=False),
        ),
    ]
