# Generated by Django 2.1.4 on 2019-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0005_newaccountlogin_issue_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatepasswords',
            name='login_account',
        ),
        migrations.RemoveField(
            model_name='duplicatepasswords',
            name='login_password',
        ),
        migrations.AddField(
            model_name='duplicatepasswords',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
    ]
