# Generated by Django 2.1.3 on 2018-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0005_auto_20181120_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHavenFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_haven_folder', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
