# Generated by Django 2.1.3 on 2018-11-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0006_newhavenfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_Name', models.CharField(max_length=200)),
                ('access_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PinaxPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_point_values', models.CharField(max_length=200)),
                ('point_values', models.CharField(max_length=200)),
            ],
        ),
    ]
