# Generated by Django 2.1.5 on 2019-02-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0007_expressloginssites_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslistofdevices',
            name='device_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
