# Generated by Django 2.1.3 on 2018-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0007_auto_20181128_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaccountlogin',
            name='userp',
            field=models.OneToOneField(default='', on_delete='CASCADE', to='comhavenapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='havenfolder',
            name='login_haven_folder',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.CharField(max_length=200),
        ),
    ]
