# Generated by Django 2.1.3 on 2018-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0008_auto_20181130_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountlogin',
            name='userp',
            field=models.OneToOneField(default=None, on_delete='CASCADE', to='comhavenapp.UserProfile'),
        ),
    ]
