# Generated by Django 2.1.5 on 2019-02-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0008_accesslistofdevices_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_stats',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
