# Generated by Django 2.1.3 on 2018-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0009_auto_20181130_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountlogin',
            name='userp',
            field=models.OneToOneField(on_delete='CASCADE', to='comhavenapp.UserProfile'),
        ),
    ]
