# Generated by Django 2.1.3 on 2018-11-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0010_auto_20181130_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountlogin',
            name='userp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comhavenapp.UserProfile'),
        ),
    ]
