# Generated by Django 2.1.5 on 2019-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0010_auto_20190210_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslistofdevices',
            name='device_name',
            field=models.CharField(default='Windows-PC', max_length=30),
        ),
        migrations.AlterField(
            model_name='accesslistofdevices',
            name='device_platform',
            field=models.CharField(default='Windows', max_length=30),
        ),
    ]
