# Generated by Django 2.1.5 on 2019-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0011_auto_20190211_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountlogin',
            name='login_notes',
            field=models.CharField(max_length=200, verbose_name='notes'),
        ),
    ]
