# Generated by Django 2.1.3 on 2018-11-30 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0011_auto_20181130_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
