# Generated by Django 2.1.5 on 2019-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0012_auto_20190212_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaccountlogin',
            name='login_tp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='newaccountlogin',
            name='login_notes',
            field=models.CharField(max_length=200),
        ),
    ]
