# Generated by Django 2.1.3 on 2018-11-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0012_auto_20181130_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newaccountlogin',
            old_name='userp',
            new_name='user',
        ),
    ]
