# Generated by Django 2.1.3 on 2018-11-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0013_auto_20181130_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newaccountlogin',
            name='user',
        ),
    ]
