# Generated by Django 2.1.5 on 2019-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0014_auto_20190220_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitychallenges',
            name='status',
            field=models.CharField(default='Unfinished', max_length=255),
        ),
    ]
