# Generated by Django 2.1.5 on 2019-03-17 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comhavenapp', '0015_auto_20190317_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Unfinished', max_length=255)),
                ('tasks', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comhavenapp.Tasks', to_field='tasks')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
