# Generated by Django 2.1.3 on 2018-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhavenapp', '0016_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessListOfDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='NewHavenFolder',
        ),
        migrations.RemoveField(
            model_name='newaccountlogin',
            name='login_haven_folder',
        ),
        migrations.DeleteModel(
            name='HavenFolder',
        ),
    ]
